version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: pug-code-gen
    versions:
    - 3.0.2
  - dependency-name: pug
    versions:
    - 3.0.1
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 99
